/* Curated local recipe database — 8 per meal type, all pre-validated
   against MEAL_TARGETS and the FORBIDDEN_* lists. Macros are estimated
   for fields where the original data only carried protein+kcal; rough
   carbs/fat values support the training-day carb bonus heuristic. */

const COLAZIONE = [
  {
    id: "c1", source: "local", name: "Uova e Avena", name_it: "Uova e Avena",
    meal_types: ["colazione"],
    protein_g: 38, kcal: 520, carbs_g: 48, fat_g: 20,
    active_prep_minutes: 5, total_minutes: 5,
    ingredients: ["4 uova", "30g avena", "200ml latte", "1 banana", "caffè"],
    steps: [
      "Sbatti le uova e cuoci a fuoco basso mescolando.",
      "Mescola avena, latte e banana a pezzi.",
      "Tip: prepara l'avena la sera prima.",
    ],
    batch_friendly: false, one_pan: true, no_cook: false,
    protein_source: "eggs", difficulty: 1,
    tags: ["quick", "italian"], image_url: null,
  },
  {
    id: "c2", source: "local", name: "Pancakes Proteici", name_it: "Pancakes Proteici",
    meal_types: ["colazione"],
    protein_g: 35, kcal: 490, carbs_g: 50, fat_g: 16,
    active_prep_minutes: 10, total_minutes: 10,
    ingredients: ["3 uova", "50g avena macinata", "100g yogurt greco", "1 banana matura", "cannella"],
    steps: [
      "Frulla tutti gli ingredienti.",
      "Cuoci cucchiaiate in padella antiaderente, 2 min per lato.",
      "Servi con frutta fresca.",
    ],
    batch_friendly: false, one_pan: true, no_cook: false,
    protein_source: "eggs", difficulty: 1,
    tags: ["quick", "italian"], image_url: null,
  },
  {
    id: "c3", source: "local", name: "Frittata Verde", name_it: "Frittata Verde",
    meal_types: ["colazione"],
    protein_g: 40, kcal: 450, carbs_g: 8, fat_g: 30,
    active_prep_minutes: 8, total_minutes: 8,
    ingredients: ["4 uova", "50g spinaci", "30g parmigiano", "olio EVO", "sale e pepe"],
    steps: [
      "Sbatti uova con parmigiano.",
      "Scalda olio, salta gli spinaci 1 min, aggiungi le uova.",
      "Cuoci 3 min a fuoco medio, 2 min sotto il grill.",
    ],
    batch_friendly: false, one_pan: true, no_cook: false,
    protein_source: "eggs", difficulty: 1,
    tags: ["quick", "italian"], image_url: null,
  },
  {
    id: "c4", source: "local", name: "Toast al Salmone", name_it: "Toast al Salmone",
    meal_types: ["colazione"],
    protein_g: 36, kcal: 480, carbs_g: 32, fat_g: 22,
    active_prep_minutes: 5, total_minutes: 5,
    ingredients: ["2 fette pane integrale", "3 uova", "50g salmone affumicato", "¼ avocado", "limone"],
    steps: [
      "Tosta il pane.",
      "Cuoci le uova in camicia 3 min.",
      "Spalma l'avocado, aggiungi salmone e uova.",
    ],
    batch_friendly: false, one_pan: false, no_cook: false,
    protein_source: "fish", difficulty: 2,
    tags: ["quick"], image_url: null,
  },
  {
    id: "c5", source: "local", name: "Cottage Cheese e Frutta", name_it: "Cottage Cheese e Frutta",
    meal_types: ["colazione"],
    protein_g: 36, kcal: 420, carbs_g: 38, fat_g: 12,
    active_prep_minutes: 2, total_minutes: 2,
    ingredients: ["200g cottage cheese", "100g frutti di bosco", "1 tbsp miele", "30g granola"],
    steps: [
      "Versa il cottage cheese in una ciotola.",
      "Aggiungi frutta, granola e miele.",
    ],
    batch_friendly: true, one_pan: false, no_cook: true,
    protein_source: "dairy", difficulty: 1,
    tags: ["no-cook", "quick"], image_url: null,
  },
  {
    id: "c6", source: "local", name: "Shake Proteico con Avena", name_it: "Shake Proteico con Avena",
    meal_types: ["colazione"],
    protein_g: 40, kcal: 490, carbs_g: 52, fat_g: 12,
    active_prep_minutes: 3, total_minutes: 3,
    ingredients: ["30g whey protein", "50g avena", "200ml latte", "1 banana", "1 cucchiaio burro mandorle"],
    steps: ["Frulla tutti gli ingredienti per 30 secondi."],
    batch_friendly: false, one_pan: false, no_cook: true,
    protein_source: "mixed", difficulty: 1,
    tags: ["no-cook", "quick"], image_url: null,
  },
  {
    id: "c7", source: "local", name: "Uova al tegamino con pane integrale", name_it: "Uova al tegamino",
    meal_types: ["colazione"],
    protein_g: 35, kcal: 460, carbs_g: 30, fat_g: 22,
    active_prep_minutes: 5, total_minutes: 5,
    ingredients: ["3 uova", "2 fette pane integrale", "olio EVO", "sale", "pepe"],
    steps: [
      "Scalda olio in padella.",
      "Rompi le uova e cuoci 3 min.",
      "Tosta il pane nel frattempo.",
    ],
    batch_friendly: false, one_pan: true, no_cook: false,
    protein_source: "eggs", difficulty: 1,
    tags: ["quick"], image_url: null,
  },
  {
    id: "c8", source: "local", name: "Yogurt Greco con Mandorle", name_it: "Yogurt Greco con Mandorle",
    meal_types: ["colazione"],
    protein_g: 38, kcal: 480, carbs_g: 36, fat_g: 20,
    active_prep_minutes: 2, total_minutes: 2,
    ingredients: ["250g yogurt greco 0%", "30g mandorle", "1 banana", "miele", "cannella"],
    steps: [
      "Versa lo yogurt in una ciotola.",
      "Aggiungi mandorle, banana a fette, miele e cannella.",
    ],
    batch_friendly: false, one_pan: false, no_cook: true,
    protein_source: "dairy", difficulty: 1,
    tags: ["no-cook", "quick"], image_url: null,
  },
];

const PRANZO = [
  {
    id: "p1", source: "local", name: "Bowl Riso e Pollo", name_it: "Bowl Riso e Pollo",
    meal_types: ["pranzo"],
    protein_g: 52, kcal: 650, carbs_g: 72, fat_g: 14,
    active_prep_minutes: 10, total_minutes: 10,
    ingredients: ["200g petto di pollo", "200g riso precotto", "100g zucchine", "aglio", "rosmarino", "olio EVO"],
    steps: [
      "Cuoci il pollo a pezzi in padella con aglio e rosmarino, 6-7 min.",
      "Aggiungi zucchine 3 min.",
      "Mescola col riso.",
    ],
    batch_friendly: true, one_pan: true, no_cook: false,
    protein_source: "chicken", difficulty: 1,
    tags: ["quick", "italian"], image_url: null,
  },
  {
    id: "p2", source: "local", name: "Pasta al Tonno", name_it: "Pasta al Tonno",
    meal_types: ["pranzo"],
    protein_g: 48, kcal: 620, carbs_g: 70, fat_g: 12,
    active_prep_minutes: 12, total_minutes: 12,
    ingredients: ["80g pasta integrale", "160g tonno al naturale", "200g pomodorini", "capperi", "origano"],
    steps: [
      "Cuoci la pasta.",
      "In padella: olio, pomodorini 5 min, poi tonno e capperi.",
      "Mescola tutto.",
    ],
    batch_friendly: true, one_pan: false, no_cook: false,
    protein_source: "fish", difficulty: 1,
    tags: ["italian"], image_url: null,
  },
  {
    id: "p3", source: "local", name: "Salmone con Riso", name_it: "Salmone con Riso",
    meal_types: ["pranzo"],
    protein_g: 55, kcal: 680, carbs_g: 60, fat_g: 22,
    active_prep_minutes: 10, total_minutes: 10,
    ingredients: ["200g filetto salmone", "200g riso precotto", "limone", "aneto", "olio EVO", "insalata"],
    steps: [
      "Padella antiaderente calda.",
      "Cuoci il salmone 4 min per lato con limone e aneto.",
      "Servi con riso e insalata.",
    ],
    batch_friendly: false, one_pan: true, no_cook: false,
    protein_source: "fish", difficulty: 2,
    tags: ["italian"], image_url: null,
  },
  {
    id: "p4", source: "local", name: "Bowl di Ceci", name_it: "Bowl di Ceci",
    meal_types: ["pranzo"],
    protein_g: 44, kcal: 600, carbs_g: 78, fat_g: 14,
    active_prep_minutes: 5, total_minutes: 5,
    ingredients: ["200g ceci in scatola", "200g riso precotto", "pomodori", "cetriolo", "olio EVO", "cumino"],
    steps: [
      "Scola i ceci.",
      "Mescola tutto con olio, limone e cumino. Zero cottura.",
    ],
    batch_friendly: true, one_pan: false, no_cook: true,
    protein_source: "legumes", difficulty: 1,
    tags: ["no-cook", "quick"], image_url: null,
  },
  {
    id: "p5", source: "local", name: "Sgombro e Patate", name_it: "Sgombro e Patate",
    meal_types: ["pranzo"],
    protein_g: 46, kcal: 590, carbs_g: 50, fat_g: 22,
    active_prep_minutes: 5, total_minutes: 5,
    ingredients: ["160g sgombro in scatola", "200g patate lessate", "prezzemolo", "cipolla", "olio EVO"],
    steps: ["Mescola sgombro scolato con patate, cipolla, prezzemolo, olio e aceto."],
    batch_friendly: false, one_pan: false, no_cook: true,
    protein_source: "fish", difficulty: 1,
    tags: ["no-cook", "quick"], image_url: null,
  },
  {
    id: "p6", source: "local", name: "Insalata di Tonno e Fagioli", name_it: "Insalata di Tonno e Fagioli",
    meal_types: ["pranzo"],
    protein_g: 48, kcal: 580, carbs_g: 50, fat_g: 16,
    active_prep_minutes: 5, total_minutes: 5,
    ingredients: ["160g tonno al naturale", "200g fagioli cannellini", "pomodori", "cipolla", "olio EVO", "aceto"],
    steps: [
      "Scola tonno e fagioli.",
      "Taglia i pomodori e la cipolla.",
      "Mescola tutto con olio e aceto.",
    ],
    batch_friendly: false, one_pan: false, no_cook: true,
    protein_source: "fish", difficulty: 1,
    tags: ["no-cook", "quick"], image_url: null,
  },
  {
    id: "p7", source: "local", name: "Petto di Pollo con Rucola", name_it: "Petto di Pollo con Rucola",
    meal_types: ["pranzo"],
    protein_g: 52, kcal: 520, carbs_g: 8, fat_g: 22,
    active_prep_minutes: 12, total_minutes: 12,
    ingredients: ["200g petto di pollo", "rucola", "pomodorini", "parmigiano", "olio EVO", "limone"],
    steps: [
      "Cuoci il pollo in padella 5 min per lato.",
      "Taglia a fette.",
      "Servi su rucola condita.",
    ],
    batch_friendly: true, one_pan: true, no_cook: false,
    protein_source: "chicken", difficulty: 2,
    tags: ["italian"], image_url: null,
  },
  {
    id: "p8", source: "local", name: "Uova Strapazzate su Farro", name_it: "Uova Strapazzate su Farro",
    meal_types: ["pranzo"],
    protein_g: 46, kcal: 610, carbs_g: 60, fat_g: 22,
    active_prep_minutes: 10, total_minutes: 10,
    ingredients: ["4 uova", "150g farro precotto", "50g spinaci", "parmigiano", "olio EVO"],
    steps: [
      "Scalda il farro.",
      "Cuoci le uova strapazzate con spinaci.",
      "Mescola e servi.",
    ],
    batch_friendly: false, one_pan: true, no_cook: false,
    protein_source: "eggs", difficulty: 1,
    tags: ["quick"], image_url: null,
  },
];

const CENA = [
  {
    id: "d1", source: "local", name: "Teglia di Pollo", name_it: "Teglia di Pollo",
    meal_types: ["cena"],
    protein_g: 52, kcal: 480, carbs_g: 24, fat_g: 22,
    active_prep_minutes: 5, total_minutes: 35,
    ingredients: ["250g cosce di pollo", "peperoni", "zucchine", "pomodorini", "aglio", "paprika", "olio EVO"],
    steps: [
      "Disponi tutto su una teglia con olio e spezie.",
      "Forno 200° per 30 min.",
    ],
    batch_friendly: true, one_pan: true, no_cook: false,
    protein_source: "chicken", difficulty: 1,
    tags: ["oven", "passive"], image_url: null,
  },
  {
    id: "d2", source: "local", name: "Bistecca con Rucola", name_it: "Bistecca con Rucola",
    meal_types: ["cena"],
    protein_g: 56, kcal: 520, carbs_g: 8, fat_g: 28,
    active_prep_minutes: 10, total_minutes: 12,
    ingredients: ["250g controfiletto", "rucola", "pomodori", "parmigiano a scaglie", "olio EVO", "limone"],
    steps: [
      "Piastra al massimo.",
      "Bistecca 3-4 min per lato, riposa 2 min.",
      "Servi su rucola.",
    ],
    batch_friendly: false, one_pan: true, no_cook: false,
    protein_source: "beef", difficulty: 2,
    tags: ["italian"], image_url: null,
  },
  {
    id: "d3", source: "local", name: "Merluzzo al Forno", name_it: "Merluzzo al Forno",
    meal_types: ["cena"],
    protein_g: 50, kcal: 420, carbs_g: 12, fat_g: 16,
    active_prep_minutes: 5, total_minutes: 25,
    ingredients: ["250g filetto merluzzo", "olive", "capperi", "pomodori", "aglio", "prezzemolo", "olio EVO"],
    steps: [
      "Disponi il pesce in pirofila con olive, capperi, pomodori.",
      "Forno 200° per 20 min.",
    ],
    batch_friendly: false, one_pan: true, no_cook: false,
    protein_source: "fish", difficulty: 1,
    tags: ["oven", "passive"], image_url: null,
  },
  {
    id: "d4", source: "local", name: "Burger di Manzo", name_it: "Burger di Manzo",
    meal_types: ["cena"],
    protein_g: 54, kcal: 560, carbs_g: 14, fat_g: 30,
    active_prep_minutes: 12, total_minutes: 12,
    ingredients: ["250g carne macinata manzo", "insalata", "pomodoro", "avocado", "spezie burger"],
    steps: [
      "Forma due hamburger e condisci.",
      "Padella 4 min per lato.",
      "Servi con insalata e avocado.",
    ],
    batch_friendly: true, one_pan: true, no_cook: false,
    protein_source: "beef", difficulty: 1,
    tags: ["quick"], image_url: null,
  },
  {
    id: "d5", source: "local", name: "Gamberi Saltati", name_it: "Gamberi Saltati",
    meal_types: ["cena"],
    protein_g: 48, kcal: 440, carbs_g: 22, fat_g: 14,
    active_prep_minutes: 10, total_minutes: 10,
    ingredients: ["250g gamberi sgusciati", "broccoli", "peperoni", "aglio", "zenzero", "salsa di soia light"],
    steps: [
      "Padella molto calda.",
      "Verdure 3 min, gamberi 2 min.",
      "Aggiungi salsa di soia e zenzero, salta 1 min.",
    ],
    batch_friendly: false, one_pan: true, no_cook: false,
    protein_source: "fish", difficulty: 2,
    tags: ["quick"], image_url: null,
  },
  {
    id: "d6", source: "local", name: "Salmone al Forno con Verdure", name_it: "Salmone al Forno con Verdure",
    meal_types: ["cena"],
    protein_g: 52, kcal: 450, carbs_g: 18, fat_g: 20,
    active_prep_minutes: 5, total_minutes: 25,
    ingredients: ["220g filetto salmone", "broccoli", "aglio", "olio EVO", "limone"],
    steps: [
      "Disponi tutto in teglia.",
      "Condisci con olio, aglio e limone.",
      "Forno 200° per 20 min.",
    ],
    batch_friendly: false, one_pan: true, no_cook: false,
    protein_source: "fish", difficulty: 1,
    tags: ["oven", "passive"], image_url: null,
  },
  {
    id: "d7", source: "local", name: "Pollo Teriyaki Semplice", name_it: "Pollo Teriyaki Semplice",
    meal_types: ["cena"],
    protein_g: 50, kcal: 520, carbs_g: 56, fat_g: 12,
    active_prep_minutes: 15, total_minutes: 15,
    ingredients: ["250g petto di pollo", "salsa di soia light", "miele", "aglio", "riso precotto"],
    steps: [
      "Taglia il pollo a bocconi.",
      "Cuoci in padella 8 min.",
      "Aggiungi soia e miele, 2 min.",
      "Servi col riso.",
    ],
    batch_friendly: true, one_pan: true, no_cook: false,
    protein_source: "chicken", difficulty: 2,
    tags: ["quick"], image_url: null,
  },
  {
    id: "d8", source: "local", name: "Pollo alla Piastra con Verdure", name_it: "Pollo alla Piastra con Verdure",
    meal_types: ["cena"],
    protein_g: 50, kcal: 480, carbs_g: 12, fat_g: 20,
    active_prep_minutes: 12, total_minutes: 12,
    ingredients: ["250g petto di pollo", "zucchine", "peperoni", "olio EVO", "sale", "paprika"],
    steps: [
      "Scalda la piastra.",
      "Pollo 4-5 min per lato con paprika.",
      "Verdure saltate in padella 5 min.",
    ],
    batch_friendly: true, one_pan: false, no_cook: false,
    protein_source: "chicken", difficulty: 2,
    tags: ["italian"], image_url: null,
  },
];

export const RECIPES = {
  colazione: COLAZIONE,
  pranzo:    PRANZO,
  cena:      CENA,
};

export const LOCAL_RECIPES = [...COLAZIONE, ...PRANZO, ...CENA];
